### ISSUE TITLE
Downloading ChEMBL

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/few-shot-bioassays#1]
Hi @phevosp and @andrewp2303

The first step will be to download [ChEMBL](https://www.ebi.ac.uk/chembl/). Current release is 33 and [this](https://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/latest/) is the FTP page. I recommend using PostgreSQL, but feel free to decide.

As I mentioned previously, we have done some work on parsing ChEMBL. See the [chembl_ml_tools](https://github.com/ersilia-os/chembl_ml_tools) and [antimicrobial-ml-tasks](https://github.com/marcostorrework/antimicrobial-ml-tasks). However, I would recommend that you start from scratch. That will be easier in my opinion.

At the end of the procedure, we just need a (long) table that contains the following columns:
* Compound SMILES identifier (ideally, canonical SMILES).
* Assay ID
* Activity measure
* Activity units

Now, there is a bit of nuance here. For some activity units, for example, IC50, the lower the more potent the compound is. For other units, for example, % of inhibition, the higher the better. If you agree, let's discuss how we tackle this once you've had a look into the data, OK?

You will see that in the "activities" table there is a column called `PCHEMBL_VALUE`. This is a standardised value derived by ChEMBL maintainers. It is in -log scale and, in this case, the higher the better, always. Perhaps a good way to start would be to just fetch records having a non-null PCHEMBL_VALUE. This would give us a sufficiently large dataset to start with. Then we can evaluate how do we go about the other ones. In this case, the table would be even simpler:
* Compound SMILES identifier
* Assay ID
* PCHEMBL_VALUE

Feel free to decide what's best. In my opinion, we eventually want to capture all of ChEMBL activity measures, but perhaps in a first iteration only capturingt the ones that have a PCHEMBL_VALUE will suffice.

**Comment by phevosp** [comment]
Sounds great! Thanks so much for setting up the repository and outlining the next steps

**Comment by andrewp2303** [comment]
To summarize: ChEMBL has been downloaded locally for both of us, alongside postgresql 16.2 and pyscopg2 (for postgresql access using python), and we wrote a file extract_table.py that loads the relevant ChEMBL information into a csv to use for training an activity prediction model. Notably, we apply "WHERE act.pchembl_value > 0" to extract the compounds with non-null PCHEMBL_VALUEs, but it's important to note that a few extremely potent compounds could theoretically have a PCHEMBL_VALUE <= 0 — open to change in the future.
